version: '3'
services:
  service:
    build: .
    ports:
      - "8099:8000"  # Map port 8000 inside the container to port 8099 on host
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    environment:
      - PYTHONUNBUFFERED=1
